#!/bin/bash

if [ ! -d usr/share/gooroom/locale/ko/LC_MESSAGES ];then
  mkdir -p usr/share/gooroom/locale/ko/LC_MESSAGES
fi

msgfmt usr/lib/gooroom/gooroomClientServerRegister/ko.po \
	-o usr/share/gooroom/locale/ko/LC_MESSAGES/gooroom-client-server-register.mo
